### ISSUE TITLE
Incorrect status code for timed out HXR calls

### ISSUE THREAD

**Issue by quackdor** [acoustic-analytics/UICaptureSDK-Modules#7] opened 2019-10-03 15:24 UTC
Ajax listener records status code of 0 when status of 504 was observed in developer tools of the browser.

**Comment by agarridob** [comment] 2019-11-19 08:18
I can see this happening in every version, up to 1.1.4

**Comment by mpunjabi-ibm** [comment] 2020-01-08 18:10
The browser may be timing out the request before the server timeout occurs which would explain why the client side code receives a status 0 whereas the (later) server response is 504.

Can you provide the steps to reproduce this issue?

**Comment by quackdor** [comment] 2020-01-08 20:04
It's mostly page load and page transitions on a secure single page app.

**Comment by mpunjabi-aco** [comment] 2021-02-18 00:50
Closing as the issue is not reproducible.

**Closed as completed by mpunjabi-aco** 2021-02-18 00:50 UTC
