### ISSUE TITLE
Negative interaction with app code

### ISSUE THREAD

**Issue by quackdor** [acoustic-analytics/UICaptureSDK-Modules#8] opened 2020-01-07 22:12 UTC
Seeing an issue where ajax listener is interacting negatively with the application it's enabled on.  It appears to  cause the code to execute in some way.  This is also causing performance impact.  This is the 1.1.4 version. This problem did not seem to exist prior to 1.1.4.

**Comment by quackdor** [comment] 2020-01-07 22:17
I've also opened support case TS003199849 for this

**Comment by quackdor** [comment] 2020-01-08 17:41
This issue appears to be isolated to the 5.6 core.  It doesn't happen with the 5.5 core.

**Comment by mpunjabi-ibm** [comment] 2020-01-08 18:16
Please provide information that will help us reproduce and analyze the issue. Refer to the following link:
https://github.com/ibm-watson-cxa/UICaptureSDK-Modules/tree/master/AjaxListener#issues

**Comment by quackdor** [comment] 2020-01-08 19:57
Module Version:
1.1.4

Current Behavior:
When clicks occur ajax calls for images were occurring and showed the Tealeaf JS file as the initiator.  In a couple areas there was performance degradation when items were added to the DOM.  

Expected Behavior
Image files would not be called by the Tealeaf js when clicks occur on any objects. 

Steps to Reproduce
For now you can go to the login page for my.cigna.com and click around in random areas and see the Tealeaf js appear to trigger files to be called.  It's mostly one single file.

**Comment by mpunjabi-ibm** [comment] 2020-01-21 01:10
Thank you for the details. After analysis, this has been confirmed to be a Chrome browser specific issue related to the cloneNode() API.

Closing since this is not an Ajax Listener issue. Additional follow-up in the support ticket.

**Closed as completed by mpunjabi-ibm** 2020-01-21 01:10 UTC
